// <auto-generated />
namespace DirectDebits.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FeatureFlags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeatureFlags));
        
        string IMigrationMetadata.Id
        {
            get { return "201807232059014_FeatureFlags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
